#include "textlines.h"

// Helper Text
CHAR16 *helpLines[] = {
    L"====================================================\r\n",
    L" DASE SHELL - HELP\r\n",
    L"====================================================\r\n",
    L" Commands are NOT case-sensitive.\r\n",
    L"\r\n",
    L" help\r\n",
    L"   Display this help message\r\n",
    L"   Usage: help\r\n",
    L"\r\n",
    L" exit\r\n",
    L"   Exit the shell\r\n",
    L"   Usage: exit\r\n",
    L"\r\n",
    L" clear\r\n",
    L"   Clear the screen\r\n",
    L"   Usage: clear\r\n",
    L"\r\n",
    L" list\r\n",
    L"   List files in the current directory\r\n",
    L"   Usage: list\r\n",
    L"   Flags:\r\n",
    L"     -r        Recursive listing for recognized dirs\r\n",
    L"     -dX       List disk number X\r\n",
    L"     -sdXparY  List disk X, partition Y\r\n",
    L"     -p        Define what path to list\r\n",
    L"\r\n",
    L" listdisks\r\n",
    L"   List all disks in the system (appear as diskX)\r\n",
    L"   Usage: listdisks\r\n",
    L"\r\n",
    L" listparts\r\n",
    L"   List all partitions in disk X\r\n",
    L"   (appear as diskXpartY)\r\n",
    L"   Usage: listparts X\r\n",
    L"\r\n",
    L" cd\r\n",
    L"   Change the current directory\r\n",
    L"   Usage: cd /disk0part1/\r\n",
    L"          cd /path/to/dir\r\n",
    L"\r\n",
    L" cat\r\n",
    L"   Display the contents of a file\r\n",
    L"   Usage: cat /path/to/file\r\n",
    L"\r\n",
    L" wipe\r\n",
    L"   Wipe a disk or partition\r\n",
    L"   Usage: wipe\r\n",
    L"   Flags:\r\n",
    L"     (none)    Enters CLI mode\r\n",
    L"     -dX       Selects disk X to wipe\r\n",
    L"     -x        Executes wipe on selected disk(s)\r\n",
    L"\r\n",
    L" smartscan\r\n",
    L"   Scans for file extensions in the system\r\n",
    L"   Usage: smartscan \"ext1\" \"ext2\" ...\r\n",
    L"   Example: smartscan \"word\" \"png\" \"pdf\"\r\n",
    L"\r\n",
    L"====================================================\r\n",
};

CONST UINTN helpLineCount = sizeof(helpLines) / sizeof(helpLines[0]);