#include "textlines.h"

// Helper Text
CHAR16 *helpLines[] = {
    L"====================================================\r\n",
    L" DASE SHELL - HELP\r\n",
    L"====================================================\r\n",
    L" Commands are case-sensitive (type them in lowercase).\r\n",
    L"\r\n",
    L"----------------------------------------------------\r\n",
    L" GENERAL\r\n",
    L"----------------------------------------------------\r\n",
    L" help\r\n",
    L"   Display this help message\r\n",
    L"   Usage: help\r\n",
    L"\r\n",
    L" clear\r\n",
    L"   Clear the screen\r\n",
    L"   Usage: clear\r\n",
    L"\r\n",
    L" exit\r\n",
    L"   Power off the machine\r\n",
    L"   Usage: exit\r\n",
    L"\r\n",
    L"----------------------------------------------------\r\n",
    L" DISKS\r\n",
    L"----------------------------------------------------\r\n",
    L" listdisks\r\n",
    L"   List all disks (appear as diskX) and mark the\r\n",
    L"   one DASE booted from\r\n",
    L"   Usage: listdisks\r\n",
    L"\r\n",
    L" listparts\r\n",
    L"   List all partitions on disk X\r\n",
    L"   (appear as diskXpartY)\r\n",
    L"   Usage: listparts X\r\n",
    L"\r\n",
    L" listdisksinfo\r\n",
    L"   Show each disk's controller, transport and size\r\n",
    L"   Usage: listdisksinfo\r\n",
    L"\r\n",
    L" listatainfo\r\n",
    L"   Show model, serial and media type of SATA/IDE\r\n",
    L"   disks\r\n",
    L"   Usage: listatainfo\r\n",
    L"\r\n",
    L" nvmeinfo\r\n",
    L"   Show model, serial, namespaces and supported\r\n",
    L"   erase commands of NVMe disks\r\n",
    L"   Usage: nvmeinfo\r\n",
    L"\r\n",
    L"----------------------------------------------------\r\n",
    L" WIPING\r\n",
    L"----------------------------------------------------\r\n",
    L" checkwipe\r\n",
    L"   Show whether each disk can be wiped, and how\r\n",
    L"   Usage: checkwipe\r\n",
    L"          checkwipe X\r\n",
    L"\r\n",
    L" wipe\r\n",
    L"   Select disks, then wipe and verify them. The\r\n",
    L"   selection is kept between commands and every\r\n",
    L"   disk is re-checked before anything is written.\r\n",
    L"   Usage: wipe [flags]\r\n",
    L"   Flags:\r\n",
    L"     (none)    Show the current selection\r\n",
    L"     -dX       Select disk X\r\n",
    L"     -rdX      Deselect disk X\r\n",
    L"     -a        Select every disk that can be wiped\r\n",
    L"     -l        Show the current selection\r\n",
    L"     -c        Clear the selection\r\n",
    L"     -x        Wipe the selected disks\r\n",
    L"               (you must type  I confirm  first)\r\n",
    L"     -s        With -x: wipe one disk at a time\r\n",
    L"   -d and -rd cannot be combined with other flags.\r\n",
    L"   Example: wipe -d3 -d4    then    wipe -x\r\n",
    L"\r\n",
    L"   Method per disk type:\r\n",
    L"     HDD       Overwrite every block with zeros\r\n",
    L"     NVMe      Sanitize, or Format with User Data\r\n",
    L"               Erase if Sanitize is unsupported\r\n",
    L"               (single-namespace drives only)\r\n",
    L"     SATA SSD  Not supported yet\r\n",
    L"   Every wipe is verified by reading the whole disk\r\n",
    L"   back. The boot disk, RAID volumes and disks of\r\n",
    L"   unknown media type are always refused.\r\n",
    L"\r\n",
    L"----------------------------------------------------\r\n",
    L" DIAGNOSTICS\r\n",
    L"----------------------------------------------------\r\n",
    L" fat32test\r\n",
    L"   Mount the FAT32 volume on disk0 and print its\r\n",
    L"   file tree\r\n",
    L"   Usage: fat32test\r\n",
    L"\r\n",
    L"====================================================\r\n",
};

CONST UINTN helpLineCount = sizeof(helpLines) / sizeof(helpLines[0]);
